[package]
name = "sql"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.196"
serde_json = "1.0.113"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
